### PR TITLE
Update Configuration_Delta.h

### PR DESCRIPTION
**Pull request by Briangsouza**

### CODE REVIEW

**Comment by clefranc** [comment]
@Briangsouza Hi, I'm very interested in your delta correction code. Can you add more information on how properly use it? How to calculate the values? I presume I've to measure some kind of calibration print to get towers multiplier? Thank you!

**Comment by Briangsouza** [comment]
http://www.thingiverse.com/thing:745523

**Comment by MagoKimbra** [comment]
Uhm very interesting... Thank's...

**Comment by simonepri** [comment]
Closed as duplicated of: https://github.com/MagoKimbra/MarlinKimbra/pull/50

**Pull request closed without merging**
